package network

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/NimoTech/NimoOS-Common/model"
)

const (
	DnsmasqConfigDir = "/etc/dnsmasq.d"
	DnsmasqConfFile  = "/etc/dnsmasq.d/nimoos-dhcp.conf"
	NftablesConfFile = "/etc/nimoos/nat.nft"
)

// ApplyGatewayConfig scans all interfaces and configures dnsmasq and nftables
func ApplyGatewayConfig() error {
	configs, err := GetAllInterfaceConfigs()
	if err != nil {
		return fmt.Errorf("failed to get interface configs: %v", err)
	}

	var wanIfaces []string
	var lanIfaces []model.NetworkInterface

	for _, iface := range configs {
		if iface.Zone == "wan" {
			wanIfaces = append(wanIfaces, iface.Name)
		} else if iface.Zone == "lan" || (iface.Wireless != nil && iface.Wireless.Mode == "ap") {
			lanIfaces = append(lanIfaces, iface)
		} else if iface.Wireless != nil && iface.Wireless.Mode == "concurrent" {
			// Concurrent: physical interface is client (WAN), virtual AP is LAN
			wanIfaces = append(wanIfaces, iface.Name)
			apEntry := iface
			apEntry.Name = VirtualApIfacePrefix
			lanIfaces = append(lanIfaces, apEntry)
		}
	}

	// 1. Configure dnsmasq for LAN/AP interfaces
	if err := configureDnsmasq(lanIfaces); err != nil {
		return fmt.Errorf("failed to configure dnsmasq: %v", err)
	}

	// 2. Configure nftables (NAT) for WAN interfaces
	if err := configureNftables(wanIfaces); err != nil {
		return fmt.Errorf("failed to configure nftables: %v", err)
	}

	// 3. Enable IP Forwarding
	if len(wanIfaces) > 0 || len(lanIfaces) > 0 {
		if err := enableIPForwarding(); err != nil {
			return fmt.Errorf("failed to enable ip forwarding: %v", err)
		}
	}

	return nil
}

// ensureDnsmasqService creates a systemd unit for dnsmasq if one doesn't exist.
// This ensures dnsmasq is properly managed (auto-restart on crash, etc.).
func ensureDnsmasqService() error {
	// Check if systemd unit already exists
	if _, err := os.Stat("/etc/systemd/system/dnsmasq.service"); err == nil {
		return nil
	}
	if _, err := os.Stat("/lib/systemd/system/dnsmasq.service"); err == nil {
		return nil
	}

	unit := `[Unit]
Description=DHCP and DNS server (managed by NimoOS)
After=network.target

[Service]
Type=simple
ExecStart=/usr/sbin/dnsmasq -C /etc/dnsmasq.d/nimoos-dhcp.conf --no-daemon
ExecStop=/usr/bin/pkill -x dnsmasq
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
`
	if err := os.WriteFile("/etc/systemd/system/dnsmasq.service", []byte(unit), 0644); err != nil {
		return fmt.Errorf("failed to write dnsmasq unit: %w", err)
	}
	_ = exec.Command("systemctl", "daemon-reload").Run()
	_ = exec.Command("systemctl", "enable", "dnsmasq").Run()
	return nil
}

func configureDnsmasq(lanIfaces []model.NetworkInterface) error {
	if err := os.MkdirAll(DnsmasqConfigDir, 0755); err != nil {
		return err
	}

	if len(lanIfaces) == 0 {
		// No LAN/AP role: dnsmasq must not run at all. Restarting it here
		// (the old behavior) after removing its config file put systemd into
		// a permanent 5s crash loop — the unit is Restart=on-failure and
		// dnsmasq exits with status 3 when its -C file is missing.
		os.Remove(DnsmasqConfFile)
		_ = exec.Command("systemctl", "stop", "dnsmasq").Run()
		_ = exec.Command("systemctl", "disable", "dnsmasq").Run()
		return nil
	}

	// Ensure dnsmasq systemd service exists (only needed when we actually
	// serve DHCP; ensureDnsmasqService also enables the unit).
	_ = ensureDnsmasqService()

	var buf bytes.Buffer
	buf.WriteString("# Generated by NimoOS Network Engine\n")

	for _, iface := range lanIfaces {
		buf.WriteString(fmt.Sprintf("interface=%s\n", iface.Name))

		// Basic IP logic to determine DHCP range (assuming /24)
		ip := "192.168.22.1"
		if iface.IPv4 != nil && iface.IPv4.Address != "" {
			ip = iface.IPv4.Address
		} else if iface.Wireless != nil && iface.Wireless.Mode == "ap" {
			ip = "192.168.22.1"
		}

		parts := strings.Split(ip, ".")
		if len(parts) == 4 {
			prefix := fmt.Sprintf("%s.%s.%s", parts[0], parts[1], parts[2])
			buf.WriteString(fmt.Sprintf("dhcp-range=interface:%s,%s.100,%s.200,12h\n", iface.Name, prefix, prefix))
		}
	}

	if err := os.WriteFile(DnsmasqConfFile, buf.Bytes(), 0644); err != nil {
		return err
	}

	// Restart dnsmasq — try systemd first, then direct kill+start
	if err := exec.Command("systemctl", "restart", "dnsmasq").Run(); err != nil {
		// dnsmasq might not have a systemd service, try direct
		_ = exec.Command("pkill", "-x", "dnsmasq").Run()
		if err := exec.Command("dnsmasq", "-C", DnsmasqConfFile).Run(); err != nil {
			fmt.Printf("Warning: failed to start dnsmasq: %v\n", err)
		}
	}

	return nil
}

func configureNftables(wanIfaces []string) error {
	if err := os.MkdirAll("/etc/nimoos", 0755); err != nil {
		return err
	}

	if len(wanIfaces) == 0 {
		// No WAN interfaces, flush the table if it exists
		clearCmd := `
table ip nimoos_nat
delete table ip nimoos_nat
`
		os.WriteFile(NftablesConfFile, []byte(clearCmd), 0644)
		_ = exec.Command("nft", "-f", NftablesConfFile).Run()
		return nil
	}

	var buf bytes.Buffer
	buf.WriteString("table ip nimoos_nat\n")
	buf.WriteString("delete table ip nimoos_nat\n")
	buf.WriteString("table ip nimoos_nat {\n")
	buf.WriteString("    chain postrouting {\n")
	buf.WriteString("        type nat hook postrouting priority 100; policy accept;\n")

	// Create rules for each WAN interface
	for _, wan := range wanIfaces {
		buf.WriteString(fmt.Sprintf("        oifname \"%s\" masquerade\n", wan))
	}

	buf.WriteString("    }\n")
	buf.WriteString("}\n")

	if err := os.WriteFile(NftablesConfFile, buf.Bytes(), 0644); err != nil {
		return err
	}

	if err := exec.Command("nft", "-f", NftablesConfFile).Run(); err != nil {
		fmt.Printf("Warning: failed to apply nftables: %v\n", err)
	}

	return nil
}

func enableIPForwarding() error {
	// Temporary
	_ = os.WriteFile("/proc/sys/net/ipv4/ip_forward", []byte("1\n"), 0644)

	// Permanent
	confFile := "/etc/sysctl.d/99-nimoos-routing.conf"
	os.MkdirAll(filepath.Dir(confFile), 0755)
	os.WriteFile(confFile, []byte("net.ipv4.ip_forward=1\n"), 0644)
	exec.Command("sysctl", "-p", confFile).Run()

	return nil
}
