package random

import (
	"math/rand"
	"regexp"
	"strings"
	"time"
)

var (
	left = []string{
		"admiring",
		"adoring",
		"affectionate",
		"amazing",
		"awesome",
		"beautiful",
		"blissful",
		"bold",
		"brave",
		"breathtaking",
		"bright",
		"brilliant",
		"charismatic",
		"charming",
		"cheerful",
		"clever",
		"compassionate",
		"competent",
		"confident",
		"cool",
		"courageous",
		"dazzling",
		"delightful",
		"determined",
		"dreamy",
		"eager",
		"ecstatic",
		"effervescent",
		"elegant",
		"eloquent",
		"empathetic",
		"empowering",
		"encouraging",
		"energetic",
		"enlightened",
		"enthusiastic",
		"epic",
		"excellent",
		"exciting",
		"exquisite",
		"fascinating",
		"fearless",
		"fervent",
		"festive",
		"flamboyant",
		"flourishing",
		"focused",
		"friendly",
		"funny",
		"gallant",
		"generous",
		"gentle",
		"gifted",
		"glorious",
		"graceful",
		"gracious",
		"great",
		"happy",
		"hardcore",
		"harmonious",
		"heartwarming",
		"heuristic",
		"hopeful",
		"hungry",
		"illustrious",
		"imaginative",
		"impressive",
		"incredible",
		"infallible",
		"inspiring",
		"intelligent",
		"interesting",
		"intuitive",
		"invigorated",
		"invigorating",
		"joyful",
		"jovial",
		"jubilant",
		"keen",
		"kind",
		"laughing",
		"lively",
		"loving",
		"lucid",
		"magical",
		"majestic",
		"marvelous",
		"mesmerizing",
		"mindful",
		"modest",
		"musing",
		"mystifying",
		"noble",
		"nurturing",
		"optimistic",
		"passionate",
		"patient",
		"peaceful",
		"picturesque",
		"playful",
		"pleasant",
		"poetic",
		"positive",
		"powerful",
		"practical",
		"priceless",
		"proud",
		"pure",
		"quirky",
		"quizzical",
		"radiant",
		"ravishing",
		"recursing",
		"refreshing",
		"relaxed",
		"renewed",
		"resilient",
		"reverent",
		"romantic",
		"serene",
		"sharp",
		"shining",
		"sincere",
		"soothing",
		"sparkling",
		"spectacular",
		"splendid",
		"steadfast",
		"stirring",
		"stoic",
		"stunning",
		"sublime",
		"successful",
		"sweet",
		"tender",
		"thriving",
		"trusting",
		"unruffled",
		"upbeat",
		"uplifting",
		"vibrant",
		"vigilant",
		"vigorous",
		"wizardly",
		"wonderful",
		"xenodochial",
		"youthful",
		"zealous",
		"zen",
	}

	// A word list of first names, inherited from CasaOS along with the rest of
	// this package and used only to build throwaway identifiers. Feel free to
	// add your own first name.
	right = []string{
		"allen",
		"andres",
		"angelina",
		"austin",
		"bobo",
		"et",
		"ezreal",
		"grace",
		"jerry",
		"john",
		"lauren",
		"link",
		"oscar",
		"rally",
		"tiger",
		"xuhai",
		"aaron",
		"abdulrahman",
		"adrian",
		"ahmad",
		"ahmed",
		"akarsh",
		"alain",
		"alan",
		"albert",
		"albu",
		"alby",
		"alden",
		"aleks",
		"aleksander",
		"alexander",
		"alexandre",
		"alvaro",
		"alvin",
		"alyssa",
		"amor",
		"andy",
		"aner",
		"anthony",
		"antonio",
		"anuj",
		"armin",
		"atsushi",
		"barry",
		"bart",
		"belen",
		"bethany",
		"bobbie",
		"carissa",
		"cathy",
		"chiahui",
		"chorok",
		"christiaan",
		"christian",
		"christopher",
		"clara",
		"corey",
		"craig",
		"curtis",
		"danilo",
		"dave",
		"davide",
		"davina",
		"dennis",
		"derek",
		"dominic",
		"donald",
		"douglas",
		"duncan",
		"dushyanth",
		"dustin",
		"dylan",
		"earvin",
		"eduardo",
		"edward",
		"edwin",
		"ehjas",
		"eldan",
		"eleanor",
		"elina",
		"emily",
		"eric",
		"éric",
		"erik",
		"erin",
		"fabian",
		"federico",
		"felice",
		"felicyana",
		"felix",
		"feng",
		"frances",
		"frank",
		"frederic",
		"fredrik",
		"gary",
		"georgia",
		"glenn",
		"gottlieb",
		"gregoire",
		"gregory",
		"gzevd",
		"harianto",
		"harm",
		"hazel",
		"hector",
		"hidenori",
		"howard",
		"hrant",
		"jackson",
		"jaco",
		"jacob",
		"jaime",
		"jake",
		"jamaal",
		"james",
		"jan",
		"jason",
		"jean-francois",
		"jeanie",
		"jeff",
		"jeremy",
		"jeroen",
		"jess",
		"jesus",
		"jimmy",
		"joan",
		"joao",
		"joão",
		"jon",
		"jonathan",
		"jorim",
		"jorja",
		"jornack",
		"jose",
		"joshua",
		"julian",
		"jun",
		"kaity",
		"kalyn",
		"karsten",
		"kate",
		"katja",
		"ken",
		"kenichi",
		"kenneth",
		"kévin",
		"khalid",
		"kharytonov",
		"konstantinos",
		"kraisorn",
		"kurt",
		"kyle",
		"lajos",
		"lance",
		"lander",
		"lars",
		"leonardo",
		"linda",
		"lorenzo",
		"lukas",
		"magnus",
		"manuel",
		"marc",
		"marco",
		"mark",
		"markus",
		"martijn",
		"martin",
		"maryann",
		"mason",
		"matheson",
		"matthias",
		"max",
		"maxime",
		"maximilian",
		"michel",
		"michele",
		"michelle",
		"midhun",
		"miguel",
		"mikolaj",
		"mitchell",
		"mordy",
		"mr",
		"muneo",
		"mustafa",
		"naohiro",
		"navin",
		"neith",
		"nico",
		"nicolas",
		"nicole",
		"nikhil",
		"noel",
		"nrsimha",
		"ofir",
		"ohm",
		"okem",
		"owen",
		"pablo",
		"patrick",
		"pawel",
		"per",
		"pete",
		"phoenix",
		"platon",
		"prem",
		"quintin",
		"qutaiba",
		"rachid",
		"rafael",
		"raphael",
		"reid",
		"renaud",
		"renee",
		"ricardo",
		"richard",
		"rik",
		"ritesh",
		"rob",
		"rocco",
		"rodriguez",
		"romain",
		"ruben",
		"ruurd",
		"ryan",
		"samuel",
		"sapakorn",
		"sean",
		"serge",
		"shane",
		"sharlene",
		"shimada",
		"signe",
		"silasak",
		"simon",
		"steffen",
		"stylianos",
		"sultan",
		"sumie",
		"sunil",
		"takamitsu",
		"tanthep",
		"teddy",
		"thanh",
		"theodore",
		"thiago",
		"thomas",
		"tim",
		"tivy",
		"tobias",
		"todd",
		"tom",
		"tomitaka",
		"tony",
		"trung",
		"tsui",
		"tushar",
		"tyler",
		"ubs",
		"üllar",
		"vanessa",
		"wayne",
		"wen",
		"werner",
		"wolfgang",
		"wong",
		"xenia",
		"yongxin",
		"yuichi",
		"zakir",
		"zhuang",
	}
)

// asciiFold maps the accented characters that appear in the contributor names
// in `right` onto plain ASCII.
//
// The names are kept spelled correctly in the list, because that list is a
// record of who was an early backer. Folding happens here, at the point of use,
// because the main consumer is AppManagement naming a Docker Compose project
// when the user did not supply a name, and Compose rejects anything outside
// [a-z0-9_-]:
//
//	invalid project name "incredible_joão": must consist only of lowercase
//	alphanumeric characters, hyphens, and underscores
//
// Four of the names carry diacritics, which made 596 of the 40677 possible
// combinations — about one draw in seventy — a name Docker refused. That is an
// install failing for no reason the user could act on, and a test going red
// occasionally and never reproducibly.
var asciiFold = strings.NewReplacer(
	"á", "a", "à", "a", "â", "a", "ä", "a", "ã", "a", "å", "a",
	"é", "e", "è", "e", "ê", "e", "ë", "e",
	"í", "i", "ì", "i", "î", "i", "ï", "i",
	"ó", "o", "ò", "o", "ô", "o", "ö", "o", "õ", "o",
	"ú", "u", "ù", "u", "û", "u", "ü", "u",
	"ñ", "n", "ç", "c", "ß", "ss",
)

// nameSafe keeps only what a Docker Compose project name allows, after folding
// accents. It is a backstop: if a name is ever added to the lists that this
// does not anticipate, the result is still usable rather than an install error.
var nameSafe = regexp.MustCompile(`[^a-z0-9_-]`)

// Name generates a name from the lists of adjectives and contributor first
// names in this package, formatted as "adjective_name", optionally with a
// suffix. The result is always a valid Docker Compose project name.
func Name(suffix *string) string {
	return nameFrom(
		left[rand.Intn(len(left))],   //nolint:gosec // G404: Use of weak random number generator (math/rand instead of crypto/rand)
		right[rand.Intn(len(right))], //nolint:gosec // G404
		suffix,
	)
}

// nameFrom is the deterministic half of Name, so a test can walk every possible
// combination instead of sampling and hoping.
func nameFrom(adjective, name string, suffix *string) string {
	s := adjective + "_" + name
	if suffix != nil {
		s += "_" + *suffix
	}

	return nameSafe.ReplaceAllString(asciiFold.Replace(strings.ToLower(s)), "")
}

func String(n int, onlyLetters bool) string {
	return RandomString(n, onlyLetters)
}

// Deprecated: use random.String(...) instead
func RandomString(n int, onlyLetter bool) string { //nolint:revive
	var letters []rune

	if onlyLetter {
		letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")
	} else {
		letters = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789")
	}

	b := make([]rune, n)
	rand.Seed(time.Now().UnixNano())
	for i := range b {
		b[i] = letters[rand.Intn(len(letters))] //nolint:gosec // G404: Use of weak random number generator (math/rand instead of crypto/rand)
	}
	return string(b)
}
